[package]
name = "saphir_gen"
version = "0.1.0"
authors = ["richer <richer.arc@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "0.15.26"
quote = "0.6.11"
proc-macro2 = "0.4.26"